name: Deploy Supabase Edge Function

on:
  push:
    paths:
      - 'supabase/functions/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Deploy functions to Supabase
        run: |
          supabase functions deploy register-download --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
          supabase functions deploy delete-expired-files --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
